apiVersion: apps/v1
kind: Deployment
metadata:
  name: cittwosevenzero-benjamin-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cittwosevenzero-benjamin-deploy
  template:
    metadata:
      name: cittwosevenzero-benjamin-deploy
      labels:
        app: cittwosevenzero-benjamin-deploy
    spec:
      containers:
      - name: cittwosevenzero-benjamin-deploy
        image: artificialfloat/cittwosevenzero
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["npm"]
        args: ["run","start"]
        env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis-secrets-benjamin
                key: REDIS_PASS
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret: 
          secretName: ssl.secret.haein
---
apiVersion: v1
kind: Service
metadata:
  name: cittwosevenzero-benjamin-loadbalancer
spec:
  selector:
    app: cittwosevenzero-benjamin-deploy
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443